# Generated by Django 2.2 on 2022-10-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='core.Ambient')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.Ambient')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('priority', models.PositiveSmallIntegerField()),
                ('ambient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.Ambient')),
            ],
        ),
    ]
